### ISSUE TITLE
long running time and no gpu memory usage

### ISSUE THREAD

**Issue by 2019211753** [YangLing0818/SemanticSDS-3D#1]
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/dc1ad808-aeb6-4d69-8d7e-d307ad20c030">

**Comment by 2019211753** [comment]
I just followed the instruction in Qucik Start and run `python main.py --config-name=pyramid`

**Comment by 2019211753** [comment]
Sorry, GPU memory usgae is normal, is the estimated run time is normal?

**Comment by aiihn** [comment]
Thank you for your interest. [This discussion](https://github.com/gsgen3d/gsgen/issues/16) might be helpful.

**Comment by 2019211753** [comment]
> Thank you for your interest. [This discussion](https://github.com/gsgen3d/gsgen/issues/16) might be helpful.

Thanks.

**Comment by 2019211753** [comment]
> Thank you for your interest. [This discussion](https://github.com/gsgen3d/gsgen/issues/16) might be helpful.

Thanks.
